name: Ask Atom
favicon: null
layout_spectrum: 0.48799
typography_spectrum: 0.88501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1c00'
    - '#565435'
    - '#f6c27e'
    - '#7d834b'
    - '#fff2be'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
