name: Ask Atom
favicon: null
layout_spectrum: 0.48799
typography_spectrum: 0.88501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#642900'
    - '#a35f14'
    - '#e2b773'
    - '#b23710'
    - '#800000'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
