analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.5125448
  lightness: 0.375
  brandColors:
    - '#4D525B'
    - '#CFCED0'
    - '#E8AC65'
    - '#888789'
    - '#914B02'
  rhythmicContrast: 0.25
typography_spectrum: 0.3010753
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1810036
favicon: null
name: Ask Atom
