name: Ask Atom
favicon: null
layout_spectrum: 0.5564034797716886
typography_spectrum: 0.9602275770157576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9257443202659488
  lightness: 0.2747633943799883
  saturation: 0.9927938845939934
  rhythmicContrast: 0.9457295436877757
purpose: []
